import turtle

screen = 600
half = (screen / 2)
quart = (half / 2)
turtle.setup(screen + 150,screen +150)
turtle.screensize(screen + 100, screen + 100,"black")
turtle.pencolor("white")

turtle.penup()
turtle.goto(0,-quart/1.5)
turtle.pendown()
turtle.circle(quart + quart/2)
turtle.penup()
turtle.goto(-quart,quart)
turtle.pendown()
turtle.circle(quart/4)
turtle.penup()
turtle.goto(quart,quart)
turtle.pendown()
turtle.circle(quart/4)
turtle.penup()
turtle.goto(quart,quart/4)
turtle.pendown()
turtle.goto(quart,(0))
turtle.goto(-quart,0)
turtle.goto(-quart,(quart/4))
turtle.penup()
turtle.goto(0,(quart))
turtle.pendown()
turtle.goto((quart/2),quart/1.7)
turtle.goto(0,(quart/2))
turtle.penup()
turtle.goto(0,-quart/1.5)
turtle.pendown()
turtle.goto(0,-quart*1.5)
turtle.goto(0, -quart)
turtle.goto(quart/3, -quart)
turtle.goto(quart/3, -quart*1.2)
turtle.goto(quart/3, -quart)
turtle.goto(-quart/3, -quart)
turtle.goto(-quart/3, -quart*1.2)
turtle.penup()
turtle.goto(0,-quart*1.5)
turtle.pendown()
turtle.goto(quart/4, -half)
turtle.goto(0,-quart*1.5)
turtle.goto(-quart/4, -half)
turtle.exitonclick()

